import {NgModule} from '@angular/core';
import {CommonModule} from '@angular/common';


import {ScrollingModule} from '@angular/cdk/scrolling';
import {OwlDateTimeModule, OwlNativeDateTimeModule} from "ng-pick-datetime";
import {
    MatAutocompleteModule,
    MatBadgeModule,
    MatButtonModule,
    MatButtonToggleModule,
    MatCardModule,
    MatCheckboxModule,
    MatChipsModule,
    MatDatepickerModule,
    MatDialogModule, MatDividerModule,
    MatExpansionModule,
    MatFormFieldModule,
    MatGridListModule,
    MatIconModule,
    MatInputModule,
    MatListModule,
    MatMenuModule,
    MatNativeDateModule,
    MatPaginatorModule,
    MatProgressSpinnerModule,
    MatRadioModule,
    MatSelectModule,
    MatSidenavModule,
    MatSlideToggleModule,
    MatSortModule,
    MatStepperModule,
    MatTableModule,
    MatTabsModule,
    MatToolbarModule,
    MatTooltipModule
} from "@angular/material";

@NgModule({
    imports: [
        CommonModule,
        MatButtonModule,
        MatCardModule,
        MatSortModule,
        MatTableModule,
        MatInputModule,
        MatPaginatorModule,
        MatSelectModule,
        MatCheckboxModule,
        MatDatepickerModule,
        MatNativeDateModule,
        MatStepperModule,
        MatRadioModule,
        MatProgressSpinnerModule,
        MatExpansionModule,
        MatSidenavModule,
        MatListModule,
        MatFormFieldModule,
        MatIconModule,
        MatTooltipModule,
        MatToolbarModule,
        MatMenuModule,
        MatButtonToggleModule,
        MatGridListModule,
        MatSlideToggleModule,
        MatDialogModule,
        MatChipsModule,
        MatTabsModule,
        OwlDateTimeModule,
        OwlNativeDateTimeModule,
        MatAutocompleteModule,
        MatBadgeModule,
        MatDividerModule,
        ScrollingModule
    ],
    declarations: [],
    exports: [
        MatButtonModule,
        MatCardModule,
        MatSortModule,
        MatTableModule,
        MatInputModule,
        MatPaginatorModule,
        MatSelectModule,
        MatCheckboxModule,
        MatDatepickerModule,
        MatNativeDateModule,
        MatStepperModule,
        MatRadioModule,
        MatProgressSpinnerModule,
        MatExpansionModule,
        MatSidenavModule,
        MatListModule,
        MatFormFieldModule,
        MatIconModule,
        MatTooltipModule,
        MatToolbarModule,
        MatMenuModule,
        MatButtonToggleModule,
        MatGridListModule,
        MatSlideToggleModule,
        MatDialogModule,
        MatChipsModule,
        MatTabsModule,
        OwlDateTimeModule,
        OwlNativeDateTimeModule,
        MatAutocompleteModule,
        MatBadgeModule,
        MatDividerModule,
        ScrollingModule
    ]
})
export class MaterialModule {
}
